{
  "formatVersion": "1.1",
  "component": {
    "group": "martian",
    "module": "minefactorial",
    "version": "1.1.0+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.1.0+1.21.1.jar",
          "url": "minefactorial-1.1.0+1.21.1.jar",
          "size": 739719,
          "sha512": "6a5a8193a3a9aec96120208576a5384f2813051268b74453cbf967622ecf4b698df6f6ead540d41d1e85cbe3b9a661cc552237a5de116ff5ef4fcd5528256119",
          "sha256": "8b4d081660cbe42ee23c7436fbc75414f3a8238a352ea767e42cea80465db2b8",
          "sha1": "132ad9717a911095452d28c627a628d4bf4d144a",
          "md5": "116b36b35a510cd1de4196bf1835ef51"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "martian",
          "module": "regolith-neoforge",
          "version": {
            "requires": "1.1.1-beta"
          }
        },
        {
          "group": "martian",
          "module": "dapper",
          "version": {
            "requires": "1.3-beta"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.6.0"
          },
          "excludes": [
            {
              "group": "net.neoforged.fancymodloader",
              "module": "loader"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.18+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.1.0+1.21.1.jar",
          "url": "minefactorial-1.1.0+1.21.1.jar",
          "size": 739719,
          "sha512": "6a5a8193a3a9aec96120208576a5384f2813051268b74453cbf967622ecf4b698df6f6ead540d41d1e85cbe3b9a661cc552237a5de116ff5ef4fcd5528256119",
          "sha256": "8b4d081660cbe42ee23c7436fbc75414f3a8238a352ea767e42cea80465db2b8",
          "sha1": "132ad9717a911095452d28c627a628d4bf4d144a",
          "md5": "116b36b35a510cd1de4196bf1835ef51"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.1.0+1.21.1-sources.jar",
          "url": "minefactorial-1.1.0+1.21.1-sources.jar",
          "size": 492271,
          "sha512": "8e2cb790f8ac6f48106e084c51e81032a8e764223cbdd97a2ed75319ead55566c83c925f9a06cef26ebddf6cecd281d09f021e1acf8c59f1ab2f3f0acb724294",
          "sha256": "32e5f674f1b87161b02601110e4b99a07aaa2910e17a11875cd26e5ca60d801d",
          "sha1": "d68ecebd90677a3d756bd31906d8a73152b3b3a7",
          "md5": "06b50f234e4c3d50398eb4d002289a1f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.1.0+1.21.1-javadoc.jar",
          "url": "minefactorial-1.1.0+1.21.1-javadoc.jar",
          "size": 1021799,
          "sha512": "5532315fce6804c06cd8e385996ca0046ce0d1aa2741f80bfc5b0c32b470206d7bffb41ee1937a36952e8bfab9232849789fcd50d98610f99ec13747778a724b",
          "sha256": "587312ad30576154f97b9863b3ef7391a3a140ad4775a27b682cb765eb28a57a",
          "sha1": "b4b7809d7c47d4a951f6a5f5fa2c2b82fdd335b2",
          "md5": "e12eb029906a08eae31bb300bf945fcf"
        }
      ]
    }
  ]
}
