{
  "formatVersion": "1.1",
  "component": {
    "group": "martian",
    "module": "minefactorial",
    "version": "1.1.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.1.2+1.21.1.jar",
          "url": "minefactorial-1.1.2+1.21.1.jar",
          "size": 764332,
          "sha512": "0802906e1e1b0f51621020ca49b7d5fb88c84c2ab461c8c6a4eda131e37cce19db2fb0421184ffa710dc7e71b641c5500ea7f63f4f0e711c652d0ff293df026e",
          "sha256": "8f08620becf93014c49340e80598c54262f2d512bfa217d776c91e062a479ab9",
          "sha1": "1a069fb4d04d268c52b9a842bcce112578c91077",
          "md5": "9e963a584f4c9457728056f248a48b63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "martian",
          "module": "regolith-neoforge",
          "version": {
            "requires": "1.1.1-beta"
          }
        },
        {
          "group": "martian",
          "module": "dapper",
          "version": {
            "requires": "1.3-beta"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.6.0"
          },
          "excludes": [
            {
              "group": "net.neoforged.fancymodloader",
              "module": "loader"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.18+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.1.2+1.21.1.jar",
          "url": "minefactorial-1.1.2+1.21.1.jar",
          "size": 764332,
          "sha512": "0802906e1e1b0f51621020ca49b7d5fb88c84c2ab461c8c6a4eda131e37cce19db2fb0421184ffa710dc7e71b641c5500ea7f63f4f0e711c652d0ff293df026e",
          "sha256": "8f08620becf93014c49340e80598c54262f2d512bfa217d776c91e062a479ab9",
          "sha1": "1a069fb4d04d268c52b9a842bcce112578c91077",
          "md5": "9e963a584f4c9457728056f248a48b63"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.1.2+1.21.1-sources.jar",
          "url": "minefactorial-1.1.2+1.21.1-sources.jar",
          "size": 503763,
          "sha512": "23f325606c30fac2e903d72845f778722217b77da6ec418faf455dfb1a07cde26a4057f2ee3953d729449b598695300492fb911d67a3b2d33c380935a18ee4a0",
          "sha256": "3139cea57985503ab472e38578f20839a9918ce3099093bfe41baa0370e4186c",
          "sha1": "55cb2d0b2323487e8bd64c46be464c91ff34a9a2",
          "md5": "ff9ac33886cccda1ddcc47dd12fe6df4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.1.2+1.21.1-javadoc.jar",
          "url": "minefactorial-1.1.2+1.21.1-javadoc.jar",
          "size": 1076597,
          "sha512": "63ac49b837969b17dfa6025426d3a0c2af7455750ef5b0e9ce43b2ca5dc99b3b18c12dc432a99dd2e88843ba6f3abbb1383caeca057562374669113178f4f6b7",
          "sha256": "9180d90954f414d1bdce359ad6c0f19c40e84ce52b0f563654ad2946ac7203f1",
          "sha1": "48bc00b7dfd49d9b21d9d5d80d7dd1771b66aa3b",
          "md5": "769a63bffd5f814c9639b34c604fd926"
        }
      ]
    }
  ]
}
