{
  "formatVersion": "1.1",
  "component": {
    "group": "martian",
    "module": "minefactorial",
    "version": "1.1.1+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.1.1+1.21.1.jar",
          "url": "minefactorial-1.1.1+1.21.1.jar",
          "size": 764332,
          "sha512": "a249a547677ac82e0e70ab487ac6b35bfbdc49cfe7b06cb4cacdeee4aebdef9c1acd061eb124a6b018f6c9fe8c64e39722299b4f9a11306237a2e6d7c8a4fe1f",
          "sha256": "b8c39daab3138c964d3d4c70051d4510ef9c7c6076702fa1bd9390fe441e6d08",
          "sha1": "be341ee61df7fc6a4d0da3eb6cc5e10a81f8b89d",
          "md5": "cc7958067cd9adba36862625eb4a381e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "martian",
          "module": "regolith-neoforge",
          "version": {
            "requires": "1.1.1-beta"
          }
        },
        {
          "group": "martian",
          "module": "dapper",
          "version": {
            "requires": "1.3-beta"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.6.0"
          },
          "excludes": [
            {
              "group": "net.neoforged.fancymodloader",
              "module": "loader"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.18+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.1.1+1.21.1.jar",
          "url": "minefactorial-1.1.1+1.21.1.jar",
          "size": 764332,
          "sha512": "a249a547677ac82e0e70ab487ac6b35bfbdc49cfe7b06cb4cacdeee4aebdef9c1acd061eb124a6b018f6c9fe8c64e39722299b4f9a11306237a2e6d7c8a4fe1f",
          "sha256": "b8c39daab3138c964d3d4c70051d4510ef9c7c6076702fa1bd9390fe441e6d08",
          "sha1": "be341ee61df7fc6a4d0da3eb6cc5e10a81f8b89d",
          "md5": "cc7958067cd9adba36862625eb4a381e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.1.1+1.21.1-sources.jar",
          "url": "minefactorial-1.1.1+1.21.1-sources.jar",
          "size": 503763,
          "sha512": "73691e018ccc6851186f1afe57daffe1717985eae82fea738fb64c2c24b52ec6660ac07a045844eb8f7d5bd193ab794fbb24c9697df151aa2d39a1a08cdb7218",
          "sha256": "bbe16006ff3195ef65839419d56eec354712e7407bf18b89cd395b9527b2f438",
          "sha1": "2463eec4e644844201afa07e341bc0eb83c95e76",
          "md5": "3daf56a95bcf54d19844b35c4b9601ba"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.1.1+1.21.1-javadoc.jar",
          "url": "minefactorial-1.1.1+1.21.1-javadoc.jar",
          "size": 1076599,
          "sha512": "ea162110eeae593d0fc1e752e5e33fa4504261b656ac3a72f834c0ea0e5057da48f79ef700eab7f77f053fd818277bac95364f529ae1c1b84855c98f9778c3d0",
          "sha256": "e5480aa963b675c8a6b98078d15b64bad5e44f18b2ec129b6a08b618dfe1572d",
          "sha1": "38d440534b25208a91334371921ccb208cd3a5ae",
          "md5": "ce336c78b5ec3cc962b9c071939b8d95"
        }
      ]
    }
  ]
}
