{
  "formatVersion": "1.1",
  "component": {
    "group": "martian",
    "module": "minefactorial",
    "version": "1.0.2+1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.0.2+1.21.1.jar",
          "url": "minefactorial-1.0.2+1.21.1.jar",
          "size": 560479,
          "sha512": "90e8270c0c45e3b49e5370d6a0b47ee125e32214bd4f3024f437833fa544ab3e8ea97f9da0b648b56ccc32025550089e3fdd92c1fd26502b5feb61c60f8ff16c",
          "sha256": "446587c6807475464ef716732133def17334d96f28e491cefd08d0906c83bc59",
          "sha1": "32b33c7cce6bc0d673396585e3c8e04e087c509a",
          "md5": "f046c7fa44c5af3df858770b3ea8873e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "martian",
          "module": "regolith-neoforge",
          "version": {
            "requires": "1.1.1-beta"
          }
        },
        {
          "group": "martian",
          "module": "dapper",
          "version": {
            "requires": "1.3-beta"
          }
        },
        {
          "group": "thedarkcolour",
          "module": "kotlinforforge-neoforge",
          "version": {
            "requires": "5.6.0"
          },
          "excludes": [
            {
              "group": "net.neoforged.fancymodloader",
              "module": "loader"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "dev.emi",
          "module": "emi-neoforge",
          "version": {
            "requires": "1.1.18+1.21.1"
          }
        }
      ],
      "files": [
        {
          "name": "minefactorial-1.0.2+1.21.1.jar",
          "url": "minefactorial-1.0.2+1.21.1.jar",
          "size": 560479,
          "sha512": "90e8270c0c45e3b49e5370d6a0b47ee125e32214bd4f3024f437833fa544ab3e8ea97f9da0b648b56ccc32025550089e3fdd92c1fd26502b5feb61c60f8ff16c",
          "sha256": "446587c6807475464ef716732133def17334d96f28e491cefd08d0906c83bc59",
          "sha1": "32b33c7cce6bc0d673396585e3c8e04e087c509a",
          "md5": "f046c7fa44c5af3df858770b3ea8873e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.0.2+1.21.1-sources.jar",
          "url": "minefactorial-1.0.2+1.21.1-sources.jar",
          "size": 379495,
          "sha512": "edab19dfbccb9c0d698094f03a25a4ce20064304dda04c00e0cff892f0f106f37cdba6b0d19d737ca412ce30d54c01879ef7fcd4fb42c65107e8f6f6bfac2cd4",
          "sha256": "883caa137c0a04ce5635b9ec94040213f2f700141680d4c38d8abf5c3481ef76",
          "sha1": "af794031e5fd722c392d56fb5a02a1c087a64163",
          "md5": "20fe6dac30415450d989a6a0f5de8c74"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "minefactorial-1.0.2+1.21.1-javadoc.jar",
          "url": "minefactorial-1.0.2+1.21.1-javadoc.jar",
          "size": 783238,
          "sha512": "1e9b5736e67bb6ecff37a38ba599fedbea1bd8e3fa4ac2e1d0eb5d2b95e46e92e14d4540274633c714a9e1ad6929c6a4d8aeb8a91da5f70ef7f65a96540e4bce",
          "sha256": "50e6ba189fef110ec294d79deecd9d9809b54cafb2264fdfeb16672bf823a9e9",
          "sha1": "08e5f0ef427cc7a930d278be086096029acb0392",
          "md5": "7a9f44c10cdc71935b05e931a3eb7d3a"
        }
      ]
    }
  ]
}
